export const routes = {
  login: '/login',
  home: '/home',
  manageUser: '/manageUser',
  manageRoom: '/room',
  manageBooking: '/manageBooking',
  setting: '/Config',
  stat: '/stat',
  api: {
    login: '/api/login',
    logout: '/api/logout',
    refreshToken: '/api/rf-token',
    user: '/api/user/',
    room: '/api/room',
    createUser: '/api/create-user',
    service: '/api/service',
    booking_list: '/api/get-all-booking',
    notification: '/api/notification',
  },
}
