export const routes = {
  login: '/login',
  home: '/home',
  manageUser: '/manageUser',
  manageRoom: '/manageRoom',
  manageHotel: '/manageHotel',
  manageBooking: '/manageBooking',
  setting: '/setting',
  stat: '/stat',
  api: {
    login: '/api/login',
    logout: '/api/logout',
    refreshToken: '/api/rf-token',
    getProfile: '/api/get-user-by-id/',
    getUser: '/api/get-user',
    createUser: '/api/create-user',
    createHotel: '/api/create-hotel',
    getHotelList: '/api/get-hotel',
  },
};
